SELECT date,
       ticker,
       CASE WHEN ROW_NUMBER() OVER (PARTITION BY ticker ORDER BY date) < 30 
       THEN NULL 
       ELSE AVG(close) OVER (PARTITION BY ticker ORDER BY DATE ASC ROWS 30 PRECEDING) END AS mean_30,
       CASE WHEN ROW_NUMBER() OVER (PARTITION BY ticker ORDER BY date) < 90 
       THEN NULL 
       ELSE AVG(close) OVER (PARTITION BY ticker ORDER BY DATE ASC ROWS 90 PRECEDING) END AS mean_90,
       CASE WHEN ROW_NUMBER() OVER (PARTITION BY ticker ORDER BY date) < 180 
       THEN NULL 
       ELSE AVG(close) OVER (PARTITION BY ticker ORDER BY DATE ASC ROWS 180 PRECEDING) END AS mean_180
  FROM assets;
